Feature: Frontend Next JS Boilerplate
we-craft-code/bookmarks-manager pull request #4
Opened 2022-03-19 15:41 UTC by ckvignesh

Hi @evedes,

I've created the frontend folder that contains the cleaned boilerplate.

2022-03-19 19:33 UTC, evedes requested changes
Hey, good job here! Just left some minor comments ❤️

2022-03-19 19:33 UTC, evedes commented on frontend/pages/index.js
> +import styles from "../styles/Home.module.css";
Let's remove the Home.module to have a clean first boilerplate?

2022-03-19 19:33 UTC, evedes commented on frontend/pages/index.js
> +    <div className={styles.container}>
Remove all the styles for now. We'll add tailwind later.

2022-03-19 19:33 UTC, evedes commented on frontend/styles/Home.module.css
> +.container {
Let's remove this file for now? ❤️

2022-03-20 02:40 UTC, ckvignesh commented on frontend/pages/index.js
> +import styles from "../styles/Home.module.css";
Done.

2022-03-20 02:40 UTC, ckvignesh commented on frontend/pages/index.js
> +    <div className={styles.container}>
Done.

2022-03-20 02:41 UTC, ckvignesh commented on frontend/styles/Home.module.css
> +.container {
Done

2022-03-20 02:42 UTC, ckvignesh commented
Hi @evedes, I've worked on the changes you mentioned. Can you please review them?

2022-03-20 17:24 UTC, evedes approved these changes
Great job Vi, @ckvignesh ! 🔥

2022-03-20 17:24 UTC, merged

2022-03-21 01:57 UTC, ckvignesh commented
> Great job Vi, @ckvignesh ! fire

Thank you @evedes !!